# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937b00479b8168bcd8ff04b329f2f39305635d54bd272084bff3cb37f9b54ed9a0a5f22b96686fdd21253e616ba0b6845954c0131f8c75c4629ffe4cba825d0d

test:
  secret_key_base: a62a42d17f995483d6522c793c6363f43f392f607a7bfa56b43e72f1c28b004099280818ec9206a5d346bb486b716ebef216020fe7fc45678413a2c89114c330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
